name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#    - name: Minify
 #     run: |
#         find . -name "*.html" -exec npx html-minifier-terser --collapse-whitespace --remove-comments --minify-js true --minify-css true --output {} {} \;
 #        find . -name "*.css" -exec npx clean-css-cli -o {} {} \;
 #        find . -name "*.js" -exec npx terser -o {} -- {} \;

    - name: Deploy via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no orange@76.130.195.232 -p 7797 'bash -s' << 'EOF'
        # Commands to deploy your website
        cd /home/orange/
        ./server_update.sh
        # Any other deployment commands
        EOF
