# Use Github Actions to deploy the website to the server via SSH.
# Runs every merge/commit to the main branch.
name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Deploy to server
    - name: Deploy via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST_IP: ${{ secrets.HOST_IP }}
        HOST_PORT: ${{ secrets.HOST_PORT }}
      run: |
        # Access server via SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        ssh -o StrictHostKeyChecking=no orange@"$HOST_IP" -p "$HOST_PORT" 'bash -s' << 'EOF'
        
        # [[ Apache server ]]; run setup script
        cd /home/orange/
        ./update_bento.sh
        
        # Update permissions
        cd /var/www/bento.valleynas.uk
        chown orange:fruit -R /var/www/bento.valleynas.uk
        chmod 770 -R /var/www/bento.valleynas.uk
        
        exit
        rm ~/.ssh/id_rsa
        EOF